In [33]:
import numpy as np
import pandas as pd

import sklearn.datasets as sd
import sklearn.preprocessing as sp
import sklearn.feature_extraction.text as ft
import sklearn.model_selection as ms
import sklearn.linear_model as lm
import sklearn.tree as st
import sklearn.ensemble as se
import sklearn.naive_bayes as nb
import sklearn.svm as svm
import sklearn.metrics as sm

In [34]:
data = pd.read_excel("三国杀战绩统计.xlsx")
heros = data.iloc[:,3:7].values
heros = heros.reshape(-1,1)
heros

array([['界刘备'],
       ['曹植'],
       ['界甄姬'],
       ['界马超'],
       ['朱桓'],
       ['界诸葛亮'],
       ['界吕布'],
       ['蔡邕'],
       ['界诸葛亮'],
       ['秦宓'],
       ['界夏侯惇'],
       ['界李典'],
       ['界黄盖'],
       ['界夏侯惇'],
       ['界孙尚香'],
       ['刘封'],
       ['界孙坚'],
       ['界周瑜'],
       ['杜预'],
       ['黄忠'],
       ['界黄盖'],
       ['界吕布'],
       ['界马超'],
       ['界陆逊'],
       ['界马超'],
       ['刘封'],
       ['界夏侯惇'],
       ['夏侯霸'],
       ['界马超'],
       ['界刘备'],
       ['离魂婵'],
       ['曹昂'],
       ['程普'],
       ['界关羽'],
       ['孙权'],
       ['关平'],
       ['界吕布'],
       ['界周瑜'],
       ['界陆逊'],
       ['陈群'],
       ['界赵云'],
       ['黄忠'],
       ['郭图逢纪'],
       ['界关羽'],
       ['杜预'],
       ['界关羽'],
       ['界马超'],
       ['辛宪英'],
       ['界关羽'],
       ['大乔小乔'],
       ['界张辽'],
       ['界诸葛亮'],
       ['朱桓'],
       ['邓艾'],
       ['杜预'],
       ['界孙坚'],
       ['鲁肃'],
       ['许攸'],
       ['徐氏'],
       ['界刘备'],
       ['离魂婵'],
       ['许靖'],
       ['界孙尚香'],
       ['大乔小乔'],
       ['群蔡文姬'],
       ['朱桓'],
       ['界孙坚'],
       ['张春华'],
       ['荀彧'],
       ['界夏侯惇'],
       ['丁奉'],
       ['关平'],
       ['界许褚'],
       ['界大乔'],
       ['界张飞'],
       ['离魂婵'],
       ['陈群'],
       ['界关羽'],
       ['魏姜维'],
       ['界孙坚'],
       ['界关羽'],
       ['朱桓'],
       ['魏姜维'],
       ['华佗'],
       ['诸葛亮'],
       ['界吕布'],
       ['界刘备'],
       ['关平'],
       ['刘封'],
       ['界司马懿'],
       ['辛宪英'],
       ['曹昂'],
       ['界吕布'],
       ['王基'],
       ['界邓艾'],
       ['界大乔'],
       ['张春华'],
       ['曹昂'],
       ['魏姜维'],
       ['界张辽'],
       ['界甘宁'],
       ['关平'],
       ['离魂婵'],
       ['界诸葛亮'],
       ['孙鲁班'],
       ['界司马懿'],
       ['界张飞'],
       ['界关羽'],
       ['岑昏'],
       ['诸葛恪'],
       ['王基'],
       ['大乔小乔'],
       ['王基'],
       ['界刘备'],
       ['界夏侯惇'],
       ['丁奉'],
       ['界黄盖'],
       ['郭图逢纪'],
       ['魏姜维'],
       ['界刘备'],
       ['离魂婵'],
       ['界刘备'],
       ['岑昏'],
       ['界黄盖'],
       ['张春华'],
       ['夏侯霸'],
       ['秦宓'],
       ['晋张春华'],
       ['晋司马懿'],
       ['吕蒙'],
       ['黄忠'],
       ['晋司马师'],
       ['界夏侯惇'],
       ['界曹操'],
       ['界诸葛亮'],
       ['界孙坚'],
       ['界张辽'],
       ['辛宪英'],
       ['简雍'],
       ['于禁'],
       ['界周瑜'],
       ['朱桓'],
       ['蔡夫人'],
       ['界孙坚'],
       ['界黄盖'],
       ['张菖蒲'],
       ['全琮'],
       ['徐盛'],
       ['界甘宁'],
       ['晋司马师'],
       ['朱桓'],
       ['群黄月英'],
       ['夏侯霸'],
       ['陈群'],
       ['界刘备'],
       ['荀彧'],
       ['郭图逢纪'],
       ['鲁肃'],
       ['陈群'],
       ['界张飞'],
       ['界张飞'],
       ['离魂婵'],
       ['界李典'],
       ['界董卓'],
       ['界张辽'],
       ['离魂婵'],
       ['姜维'],
       ['张春华'],
       ['刘封'],
       ['界庞德'],
       ['界周瑜'],
       ['曹昂'],
       ['朱桓'],
       ['晋张春华'],
       ['貂蝉'],
       ['界孙坚'],
       ['界吕布'],
       ['界大乔'],
       ['群蔡文姬'],
       ['曹彰'],
       ['王基'],
       ['界吕布'],
       ['杜预'],
       ['界夏侯惇'],
       ['界吕布'],
       ['界大乔'],
       ['郭图逢纪'],
       ['界郭嘉'],
       ['界张辽'],
       ['卑弥呼'],
       ['离魂婵'],
       ['界孙坚'],
       ['界黄盖'],
       ['王元姬'],
       ['鲁肃'],
       ['界张辽'],
       ['大乔'],
       ['界夏侯惇'],
       ['徐盛'],
       ['界吕布'],
       ['晋司马懿'],
       ['界左慈'],
       ['魏姜维'],
       ['陈群'],
       ['界大乔'],
       ['离魂婵'],
       ['界张辽'],
       ['界张飞'],
       ['界诸葛亮'],
       ['姜维'],
       ['界张辽'],
       ['夏侯霸'],
       ['群黄月英'],
       ['大乔'],
       ['刘封'],
       ['界诸葛亮'],
       ['离魂婵'],
       ['杜预'],
       ['李严'],
       ['王元姬'],
       ['华佗'],
       ['晋司马师'],
       ['朱桓'],
       ['蔡夫人'],
       ['荀彧'],
       ['岑昏'],
       ['秦宓'],
       ['蔡夫人'],
       ['太史慈'],
       ['鲁肃'],
       ['关平'],
       ['貂蝉'],
       ['姜维'],
       ['界司马懿'],
       ['离魂婵'],
       ['界孙坚']], dtype=object)

In [35]:
encoder=sp.LabelEncoder()

data_encoded=data.copy()

data_encoded.iloc[:,3:7] = encoder.fit_transform(heros).reshape(-1,4)
data_encoded

e:\python_projects_wj\test_machine_learning\venv\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

,time,target,WJ_order,player1,player2,player3,player4,net,score,key
0,2021-08-08 11:38:00,1,1,32,25,46,55,0,NaN,NaN
1,2021-08-08 11:43:00,1,3,26,50,34,65,0,NaN,NaN
2,2021-08-08 11:50:00,0,3,50,58,36,45,0,NaN,NaN
3,2021-08-08 11:57:00,0,1,56,36,39,4,0,NaN,NaN
4,2021-08-08 12:02:00,1,1,38,35,28,77,0,NaN,NaN
5,2021-08-08 12:07:00,1,1,56,34,55,54,0,NaN,NaN
6,2021-08-08 12:12:00,0,3,55,4,36,8,0,NaN,NaN
7,2021-08-08 12:19:00,0,1,55,32,57,24,0,NaN,NaN
8,2021-08-08 12:23:00,1,3,59,31,13,3,0,NaN,NaN
9,2021-08-09 15:39:00,0,3,34,35,54,74,0,NaN,NaN
10,2021-08-09 15:44:00,1,1,51,77,73,31,0,NaN,NaN
11,2021-08-09 15:51:00,1,1,28,31,55,71,0,NaN,NaN
12,2021-08-09 15:56:00,1,3,31,10,42,50,0,NaN,NaN
13,2021-08-09 16:05:00,0,1,26,72,28,38,0,NaN,NaN
14,2021-08-09 16:13:00,0,1,76,66,18,32,0,NaN,NaN
15,2021-08-09 16:16:00,0,1,57,67,39,10,0,NaN,NaN
16,2021-08-09 16:22:00,0,1,61,26,38,16,0,NaN,NaN
17,2021-08-09 16:28:00,0,3,63,36,0,3,0,NaN,NaN
18,2021-08-09 16:32:00,1,3,49,37,43,57,0,NaN,NaN
19,2021-08-09 16:47:00,0,1,74,31,75,38,0,NaN,NaN
20,2021-08-09 16:53:00,0,3,31,26,75,5,0,NaN,NaN
21,2021-08-10 11:42:00,1,3,68,34,32,3,0,NaN,NaN
22,2021-08-10 11:46:00,0,3,4,33,71,24,0,NaN,NaN
23,2021-08-10 11:52:00,0,1,34,30,52,37,0,NaN,NaN
24,2021-08-10 11:58:00,0,3,16,24,75,42,0,NaN,NaN
25,2021-08-10 12:08:00,1,3,47,3,57,50,0,NaN,NaN
26,2021-08-17 20:58:00,0,1,14,33,43,31,-1,NaN,NaN
27,2021-08-17 21:02:00,1,1,15,69,30,10,0,NaN,NaN
28,2021-08-17 21:06:00,0,3,30,32,36,0,0,NaN,NaN
29,2021-08-17 21:21:00,0,3,56,73,75,32,-1,NaN,NaN
30,2021-08-19 18:19:00,0,2,57,32,15,56,0,1920.0,0.0
31,NaT,0,4,16,8,58,22,0,1910.0,0.0
32,NaT,0,4,21,7,77,20,0,1900.0,-1.0
33,NaT,1,4,36,44,50,38,0,1900.0,-1.0
34,NaT,1,4,42,71,60,1,0,1950.0,0.0
35,NaT,0,2,35,26,64,38,0,1960.0,0.0
36,NaT,0,2,56,17,2,19,0,1950.0,0.0
37,NaT,1,2,47,20,26,62,0,1970.0,0.0
38,NaT,1,2,8,74,32,63,0,1990.0,0.0
39,NaT,0,4,73,76,74,43,0,1970.0,0.0
40,NaT,0,2,43,57,45,48,0,1950.0,0.0
41,NaT,1,2,42,57,12,16,0,1970.0,0.0
42,NaT,1,4,4,41,35,24,0,1990.0,0.0
43,NaT,0,4,26,22,70,38,0,2000.0,1.0
44,NaT,0,4,34,37,61,23,0,2000.0,1.0
45,NaT,1,4,30,34,28,36,0,2000.0,1.0
46,NaT,0,2,34,37,73,53,0,2000.0,1.0
47,NaT,0,4,42,6,57,38,0,1950.0,0.0
48,NaT,1,2,56,29,76,42,0,1940.0,0.0
49,NaT,0,2,9,36,19,34,0,1960.0,0.0
50,NaT,1,4,21,40,75,74,0,1950.0,0.0
51,NaT,0,2,37,57,42,43,0,1970.0,0.0
52,NaT,1,4,50,12,42,8,0,1960.0,0.0
53,NaT,0,4,62,9,4,50,0,1980.0,0.0
54,NaT,1,2,57,28,27,29,0,1970.0,0.0
55,NaT,1,2,5,20,26,64,0,1990.0,0.0
56,NaT,1,2,63,15,58,64,0,2000.0,1.0
57,NaT,1,2,11,76,3,70,0,2000.0,1.0
58,NaT,1,4,12,33,57,38,0,2000.0,1.0

In [36]:
# 整理输入集与输出集
x = data_encoded.iloc[:,2:8] 
y = data.iloc[:,1] 

rand_seed = 7
train_x,test_x,train_y,test_y=\
    ms.train_test_split(x,y,test_size=0.1,stratify=y,random_state=rand_seed)

train_x.shape

(53, 6)

In [37]:
# 交叉验证
# model = lm.LogisticRegression(random_state=rand_seed)
# model = svm.SVC(kernel="linear",C=1)
# model = st.DecisionTreeClassifier(max_depth=3,min_samples_split=3,random_state=rand_seed)
model = se.RandomForestClassifier(max_depth=10,min_samples_split=3,n_estimators=200,random_state=rand_seed)
# model = nb.MultinomialNB()

score_f1 = ms.cross_val_score(model,train_x,train_y,cv=5,scoring="f1_weighted")
print(score_f1.mean())

0.5820259740259741

In [38]:
#训练模型
model.fit(train_x,train_y)
pred_test_y = model.predict(test_x)

#测试模型，评估模型
m = sm.confusion_matrix(test_y,pred_test_y) #混淆矩阵
print(m)
print(sm.classification_report(test_y,pred_test_y))

[[2 1]
 [0 3]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.75      1.00      0.86         3

    accuracy                           0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

In [40]:
new_fight_word=np.array(["界张辽","许攸","离魂婵","界夏侯惇",
                    "界司马懿","界关羽","辛宪英","界张辽",
                    "界许褚","陈群","蔡夫人","界马超",
                    "大乔小乔","朱桓","界吕布","界张辽",
                    "离魂婵","界许褚","界刘备","界诸葛亮"])
new_fight = encoder.transform(new_fight_word.reshape(-1,1)).reshape(-1,4)
WJ_order=np.array([1,2,3,4,3]).reshape(-1,1)
net=np.array([0,0,-1,0,0]).reshape(-1,1)
new_fight = np.hstack((WJ_order,new_fight,net))


pred_new_fight = model.predict(new_fight)
pred_new_fight_proba = model.predict_proba(new_fight)


pre_info_matrix = np.hstack((WJ_order,new_fight_word.reshape(-1,4),net,pred_new_fight_proba,pred_new_fight.reshape(-1,1)))
pre_info_matrix
pred_info = pd.DataFrame(pre_info_matrix,columns=["王坚出手","player1","player2","player3","player4","网络","败率","胜率","预测结果"])
pred_info

e:\python_projects_wj\test_machine_learning\venv\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

,王坚出手,player1,player2,player3,player4,网络,败率,胜率,预测结果
0,1,界张辽,许攸,离魂婵,界夏侯惇,0,0.7094166666666668,0.29058333333333336,0
1,2,界司马懿,界关羽,辛宪英,界张辽,0,0.8870833333333334,0.11291666666666668,0
2,3,界许褚,陈群,蔡夫人,界马超,-1,0.49066666666666675,0.5093333333333333,1
3,4,大乔小乔,朱桓,界吕布,界张辽,0,0.2725,0.7275,1
4,3,离魂婵,界许褚,界刘备,界诸葛亮,0,0.537,0.46299999999999997,0